language: android
android:
  components:
    
-  platform-tools
- build-tools-19.1.0


  - tools
- android-22

   

   
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - addon-google_apis-google-19
